export const candlestickTopics = [
  {
    id: 'kline-basics',
    category: 'candlestick',
    title: 'K线的构成',
    subtitle: 'Candlestick Basics',
    tags: ['基础', '入门'],
    chartId: 'kline-basics',
    sections: {
      meaning: '一根 K线记录了某一周期内的四个价格：开盘价、最高价、最低价、收盘价（合称 OHLC）。实体表示开盘与收盘之间的区间——收盘高于开盘为阳线（红），收盘低于开盘为阴线（绿）；实体上下的细线称为影线，上影线顶端为最高价，下影线底端为最低价。',
      identify: [
        '实体颜色：红阳（收>开）、绿阴（收<开）',
        '实体长度反映多空力量强弱，越长一方主导越明显',
        '上影线长说明上方抛压重，下影线长说明下方承接强',
      ],
      usage: [
        '先看实体方向与长短判断当根多空胜负',
        '再看影线位置判断关键价位的攻防',
        'K线要结合位置（高位/低位）和周期共同解读，单根意义有限',
      ],
      limitation: '单根 K线信息量有限，容易被主力用单日波动误导；务必放在趋势与成交量背景下、结合多根组合来判断。',
    },
    related: ['hammer', 'doji'],
  },
  {
    id: 'hammer',
    category: 'candlestick',
    title: '锤子线',
    subtitle: 'Hammer',
    tags: ['单根形态', '反转', '看涨'],
    chartId: 'hammer',
    sections: {
      meaning: '锤子线是出现在下跌趋势末端的单根反转形态：实体较小且位于价格区间上端，下影线很长（通常为实体的 2 倍以上），几乎没有上影线。它表明盘中虽一度大幅下探，但买方将价格强力拉回收盘，空方力量衰竭。',
      identify: [
        '出现在明显的下跌趋势之后',
        '下影线长度≥实体的 2 倍，上影线极短或没有',
        '实体颜色不限，但收红（阳）信号更强',
      ],
      usage: [
        '可视为下跌动能衰竭、潜在见底的预警',
        '需等待次日收阳或放量突破锤子线高点再确认',
        '结合支撑位、成交量萎缩后放大判断更可靠',
      ],
      limitation: '锤子线只是"可能反转"的提示而非确认信号，下跌中继时也会出现长下影；不确认就抢反弹易被套，须设好止损。',
    },
    related: ['doji', 'bullish-engulfing'],
  },
  {
    id: 'doji',
    category: 'candlestick',
    title: '十字星',
    subtitle: 'Doji',
    tags: ['单根形态', '变盘', '中性'],
    chartId: 'doji',
    sections: {
      meaning: '十字星指开盘价与收盘价几乎相等、实体极小、上下都有影线的 K线。它代表多空力量在该周期内势均力敌、市场陷入犹豫，常出现在趋势的转折或暂歇处，是重要的"变盘"信号。',
      identify: [
        '开盘与收盘价基本重合，实体接近一条横线',
        '通常上下影线都存在，长十字星变盘意义更强',
        '出现在趋势高位或低位时参考价值最大',
      ],
      usage: [
        '高位十字星警惕见顶，低位十字星留意见底',
        '把它当作"趋势可能改变"的提醒，等次日方向确认',
        '结合所处位置与成交量综合判断变盘方向',
      ],
      limitation: '十字星只说明分歧加大，并不指明方向；震荡市中频繁出现、参考价值低，必须依赖后续 K线确认。',
    },
    related: ['hammer', 'morning-star'],
  },
  {
    id: 'bullish-engulfing',
    category: 'candlestick',
    title: '看涨吞没',
    subtitle: 'Bullish Engulfing',
    tags: ['组合形态', '反转', '看涨'],
    chartId: 'bullish-engulfing',
    sections: {
      meaning: '看涨吞没由一阴一阳两根 K线组成，出现在下跌趋势末端：第一根为阴线，第二根为阳线且其实体完全包住（吞没）前一根阴线的实体。它表明买方力量在短时间内彻底压倒卖方，是较强的见底反转信号。',
      identify: [
        '出现在下跌趋势末端',
        '第二根为阳线，实体完全吞没前一根阴线实体',
        '第二根成交量明显放大，信号更可靠',
      ],
      usage: [
        '可作为试探性买入或离场观望转为偏多的依据',
        '配合成交量放大、处于支撑位附近确认度更高',
        '可将吞没阳线的低点作为止损参考',
      ],
      limitation: '在震荡市中信号频繁且容易失效；若吞没阳线放量却不能延续，可能是诱多，需结合趋势与量能过滤。',
    },
    related: ['bearish-engulfing', 'hammer'],
  },
  {
    id: 'bearish-engulfing',
    category: 'candlestick',
    title: '看跌吞没',
    subtitle: 'Bearish Engulfing',
    tags: ['组合形态', '反转', '看跌'],
    chartId: 'bearish-engulfing',
    sections: {
      meaning: '看跌吞没与看涨吞没相反，出现在上涨趋势末端：第一根为阳线，第二根为阴线且实体完全吞没前一根阳线的实体。它表明卖方力量骤然占据上风，是较强的见顶反转信号。',
      identify: [
        '出现在上涨趋势末端或高位',
        '第二根为阴线，实体完全吞没前一根阳线实体',
        '第二根放量下跌，见顶信号更强',
      ],
      usage: [
        '持仓者可视为减仓或离场的警示',
        '结合高位、放量、前期阻力位判断更可靠',
        '可将吞没阴线的高点作为反弹离场或止损参考',
      ],
      limitation: '高位震荡时也会出现假吞没；若后续快速收复阴线则信号失效，应结合趋势确认而非单根定生死。',
    },
    related: ['bullish-engulfing', 'doji'],
  },
  {
    id: 'morning-star',
    category: 'candlestick',
    title: '早晨之星',
    subtitle: 'Morning Star',
    tags: ['组合形态', '反转', '看涨'],
    chartId: 'morning-star',
    sections: {
      meaning: '早晨之星是由三根 K线组成的底部反转形态：第一根为延续跌势的大阴线；第二根为实体很小的星线（跳空或低位窄幅，多空僵持）；第三根为大阳线，深入第一根阴线实体内部。三根共同描绘出空头衰竭、多头反攻、趋势由跌转涨的过程。',
      identify: [
        '出现在下跌趋势末端',
        '中间星线实体小、与两侧拉开（理想有跳空）',
        '第三根大阳线收复第一根阴线相当部分（越多越强）',
      ],
      usage: [
        '是较可靠的底部反转组合，可作为偏多依据',
        '第三根放量、星线位置低、收复幅度大则确认度更高',
        '可将形态最低点作为止损参考',
      ],
      limitation: '形态识别较主观，A股常无跳空使其打折；仍需结合趋势、量能与支撑位确认，避免在下跌中继处误判。',
    },
    related: ['bullish-engulfing', 'hammer'],
  },
]
